# Generated by Django 5.1.4 on 2024-12-17 09:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_application_applicationtranslation_news_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='applications',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='newstranslation',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.DeleteModel(
            name='ApplicationTranslation',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
