# Generated by Django 4.2.17 on 2025-02-04 00:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_rolehierarchy_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolehierarchy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rolehierarchy',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rolehierarchy',
            name='level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rolehierarchy',
            name='role',
            field=models.CharField(default='CustomRole', max_length=50),
        ),
    ]
