# Generated by Django 4.2.16 on 2024-12-13 12:27

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0004_toolbar_toolbartranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolbarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ToolbarItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='WebSite.toolbaritem')),
            ],
            options={
                'verbose_name': 'toolbar item Translation',
                'db_table': 'WebSite_toolbaritem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='toolbartranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='toolbartranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='Toolbar',
        ),
        migrations.DeleteModel(
            name='ToolbarTranslation',
        ),
    ]
