# Generated by Django 4.2.16 on 2024-12-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0005_toolbaritem_toolbaritemtranslation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolbaritem',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
