# Generated by Django 4.2.16 on 2024-12-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0006_alter_toolbaritem_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolbaritem',
            name='position',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
