# Generated by Django 4.2.16 on 2024-12-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0007_alter_toolbaritem_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homepagecontenttranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='homepagecontenttranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='HomePageContent',
        ),
        migrations.DeleteModel(
            name='HomePageContentTranslation',
        ),
    ]
